import { z } from "zod";

export const CarDto = z.object({

  // English
  _id: z.string().optional(),
  exportCountryTo: z.string().optional(),
  vehicleType: z.string().optional(),
  exportPlateNumber: z.string().optional(),
  registrationPlateNumber: z.string().optional(),
  registrationDate: z.string().optional(),
  registrationExpiryDate: z.string().optional(),
  vehicleMake: z.string().optional(),
  category: z.string().optional(),
  modelYear: z.string().optional(),
  countryOfOrigin: z.string().optional(),
  vehicleColor: z.string().optional(),
  chassisNumber: z.string().optional(),
  engineNumber: z.string().optional(),
  numberOfDoors: z.string().optional(),
  fuelType: z.string().optional(),
  numberOfSeats: z.string().optional(),
  emptyWeight: z.string().optional(),
  insuranceCompany: z.string().optional(),
  insuranceType: z.string().optional(),
  insurancePolicyNumber: z.string().optional(),
  insuranceExpiryDate: z.string().optional(),
  ownerName: z.string().optional(),
  nationality: z.string().optional(),
  passportNumber: z.string().optional(),
  trafficCodeNumber: z.string().optional(),
  emiratesIdNumber: z.string().optional(),
  driverName: z.string().optional(),
  licenseNumber: z.string().optional(),
  driverNationality: z.string().optional(),
  licenseSource: z.string().optional(),
  certificateIssueDate: z.string().optional(),
  certificateReferenceNumber: z.string().optional(),

  // Arabic
  exportCountryToAr: z.string().optional(),
  vehicleTypeAr: z.string().optional(),
  exportPlateNumberAr: z.string().optional(),
  registrationPlateNumberAr: z.string().optional(),
  registrationDateAr: z.string().optional(),
  registrationExpiryDateAr: z.string().optional(),
  vehicleMakeAr: z.string().optional(),
  categoryAr: z.string().optional(),
  modelYearAr: z.string().optional(),
  countryOfOriginAr: z.string().optional(),
  vehicleColorAr: z.string().optional(),
  chassisNumberAr: z.string().optional(),
  engineNumberAr: z.string().optional(),
  numberOfDoorsAr: z.string().optional(),
  fuelTypeAr: z.string().optional(),
  numberOfSeatsAr: z.string().optional(),
  emptyWeightAr: z.string().optional(),
  insuranceCompanyAr: z.string().optional(),
  insuranceTypeAr: z.string().optional(),
  insurancePolicyNumberAr: z.string().optional(),
  insuranceExpiryDateAr: z.string().optional(),
  ownerNameAr: z.string().optional(),
  nationalityAr: z.string().optional(),
  driverNameAr: z.string().optional(),
  certificateIssueDateAr: z.string().optional(),
});

export const CarDtoRetrieved = z.object({
  _id: z.string().optional(),
  ownerName: z.string().optional(),
  vehicleType: z.string().optional(),
  chassisNumber: z.string().optional(),
  registrationDate: z.string().optional(),
  registrationExpiryDate: z.string().optional(),
  driverNationality: z.string().optional(),
  driverName: z.string().optional(),
  count: z.number().optional(),
});

export type CarTypeDto = z.infer<typeof CarDto>;
export type CarDtoRetrievedType = z.infer<typeof CarDtoRetrieved>;
